### ISSUE TITLE
Mission

### ISSUE THREAD

**Issue by LoeiFy** [AcyOrt/acyort#10]
### todo
- [x] ignore rss output when no set rss
- [x] server livereload
- [ ] module test
- [x] Archives paging
- [x] get image size log
- [x] local test json
- [x] cache image size
- [x] themes get config meta info
- [x] use id as path
### bug:
- [x] server: url path cannot get `index.html`
- [x] server: chinese 404 
- [x] themes: `layout.html` miss `<html>` tag
- [x] themes: post thumb src error when set `thumb_size: true`
- [x] dev mode script insert ignore `js/css/image`
### ignore

~~JSON output~~
~~theme config~~
~~hightlight.js to prismjs / line number~~
